### ISSUE TITLE
Make colorful output is discarded

### ISSUE THREAD

**Issue by rasky** [anacierdem/libdragon-docker#21]
When running `libdragon make`, all ANSI-based color is discarded from make output. This is unfortunate as the color output is very useful to highlight compilation errors and makefile information, for instance. GCC supports that but libdragon filters it out.

It looks like this depends on the way libdragon runs the make command. I'm not a nodejs expert, but looking in StackOverflow it looks like this is a known problem with `process.exec`; `process.spawn` should be used instead, with inherit flag:
https://stackoverflow.com/questions/7725809/preserve-color-when-executing-child-process-spawn/14231570#14231570

I guess this should be done only when running `make`, as in other cases you need to process the output of the spawned command and so you really need `process.exec`.

**Comment by anacierdem** [comment]
We should absolutely use `process.spawn`. Didn't have time to change it yet though :( It is still possible to read output with spawn too.

**Comment by anacierdem** [comment]
@rasky I was working on this one for a while and I'm already planning to migrate to `spawn` but couldn't make the output colorful, without even using the node wrapper and even on a docker bash. Did you have any success inside the docker container after doing `docker exec -i -t libdragon /bin/bash`? With this interactive bash, `ls` properly produce color output but `make` (and its inner commands) does not.

**Comment by anacierdem** [comment]
Even this simple recipe does not generate any color so I have started suspecting make;
```
color:
	ls /usr/local/bin
```

**Comment by anacierdem** [comment]
Then we would need to make docker redirect the colors, that is also something I couldn't make work unfortunately.

**Comment by anacierdem** [comment]
Forcing colors on ls (`docker exec -ti libdragon env TERM=xterm-256color /bin/bash -l -c "ls /usr/local/bin --color=always"`) worked, so it is probably thinking it is not available.

**Comment by rasky** [comment]
You could add `ENV TERM xterm-256color` to `Dockerfile`.

**Comment by anacierdem** [comment]
It is also possible to set them wheb running the container but that didn't change anything. An example make command with color output would be also helpful if you have a scenario in mind?

**Comment by rasky** [comment]
You can try adding -fdiagnostics-color=auto to the GCC command line. Technically, if you have a colored terminal (so with the xterm-256colors thing) this should start coloring the output.

**Comment by anacierdem** [comment]
Somehow the env vairable is not effective after the container is built. So you were right, adding to the Dockerfile fixed the docker side of things now I'm working on node to find a way.

**Comment by anacierdem** [comment]
So I have enabled colors for the wrapper but it still requires the gcc flag to enable colors. I think this resolves the current issue but we may work further on gcc to make it the default. We may need to build the toolchain with the colors enabled.

**Comment by rasky** [comment]
That's OK, it will be part of my libdragon PR to refactor the build system
