### ISSUE TITLE
Libdragon CLI 2.0

### ISSUE THREAD

**Issue by rasky** [anacierdem/libdragon-docker#34]
Given experimentation with the CLI prototype in Go, I would say that it would be great if the official tool grew these features:

 * [x] Must be able to ship as a native application on Windows, with no separate NPM installation.
 * [x] `libdragon init` that sets up a libdragon skeleton project, vendor libdragon and downloads the toolchain
   * [x] toolchain download via docker or other means (eg: zip + unpack). Could have an option to also skip altogether (if user wants to use their own toolchain).
   * [x] libdragon vendoring via subtree
   * [x] libdragon vendoring via submodules. People are opinionated on this, I think the best is to support both
   * [x] the project skeleton should come with a makefile that builds Libdragon + example ROM.
 * [x] `libdragon make` should imply `start` whenever required. In general, I would phase out `start` / `stop` as low-level / manual commands not required in most cases
   * [x] It must be very fast. It should optimistically execute `docker` just once hoping that everything will work, and then fallback to starting the container if it's not starting, then falling back to creating the container if it doesn't exist for the current repo. The correct container (per-repo) must thus be optimistically cached.
 * [x] Should automatically create one container per project, transparently.
   * [x] The container should mount the top-level git directory (if used on a git repo)
 * [x] All commands should respect the current working directory, so that you can run `make` in subdirs
 * [x] `libdragon update` should update both the libdragon vendored copy (respecting the chosen vendoring system) and the toolchain.
 * [x] `libdragon exec` as a quick way to launch things in the container, such as the libdragon tools.
   * [x] it should support interactive tools (forward stdin/stdout/stderr).
   * [x] Since libdragon tools will be compiled as part of the local libdragon copy, there must be a way to exec them without having to reinstall them every time the container is lost. Possibly launching them from the build directory or something like that. 
 * [x] `libdragon disasm` to disassemble the current elf binary (to be automatically searched in build directories and recursively, with an option to disambiguate if the project builds more than one ROM).
   * [x] This should also support disassembling only a specific symbol
 * [x] Command line help for all commands, and in general accurate user-friendly error messages (and output)
   * [x] A verbose mode that shows everything that is run is very useful for debugging

**Comment by anacierdem** [comment]
I have prepared a pre-release [here](https://github.com/anacierdem/libdragon-docker/releases/tag/v10.0.0-rc-1)
I have checked what is implemented as of now with a few notes;

- There is no skeleton project yet
- `libdragon make` is implemented to be fast, but there still will be scripting overhead, so there is no 'very fast' guarantee yet.
- It is possible to do `libdragon init` at an NPM project's or git root
> Since libdragon tools will be compiled as part of the local libdragon copy, there must be a way to exec them without having to reinstall them every time the container is lost. Possibly launching them from the build directory or something like that.
- Currently I invoke `build.sh` which start with a clean step. Once we set things up better at main repo, I think we can solve this as the mounted file system is persistent.

**Comment by rasky** [comment]
> libdragon bash to start an interactive shell session

I usually do `libdragon exec bash` with my tool

**Comment by anacierdem** [comment]
>toolchain download via docker or other means (eg: zip + unpack). Could have an option to also skip altogether (if user wants to use their own toolchain).

This is very easy to do with [`docker load`](https://docs.docker.com/engine/reference/commandline/load/) which an advanced enough users wouldn't mind doing themselves, so I'm assuming this already exists.

>Since libdragon tools will be compiled as part of the local libdragon copy, there must be a way to exec them without having to reinstall them every time the container is lost. Possibly launching them from the build directory or something like that.

If we decide to go towards `docker compose` this almost becomes trivial to implement. Still possible with the current architecture but will require some housekeeping. I will work on this later -> #53

Closing this issue 🎊
