### ISSUE TITLE
Add the warning about existing libdragon

### ISSUE THREAD

**Issue by anacierdem** [anacierdem/libdragon-docker#57]
The tool used to show an explicit warning when it finds a file named libdragon in the project directory.

Some git version on Windows or some system configuration is making git think it is an existing prefix and breaks submodule operations.

Let's introduce the warning back and expand the docs to suggest adding the tool to the `PATH`.

These are the known git versions having the issue if it has anything to do with git;
`2.32.0.windows.2`
`2.30.2`

**Comment by JasonCampbell256** [comment]
As the user that encountered this I would be happy to test the warning once it is implemented.
