### ISSUE TITLE
Deps for building OpenGL projects in the Docker image

### ISSUE THREAD

**Issue by Miserlou** [anacierdem/libdragon-docker#65]
I'm trying to build this project with libdragon-docker https://github.com/Dragorn421/n64homebrew/tree/main/brew3d but it chokes on 

```
#include <GL/gl.h>
#include <GL/glu.h>
#include <GL/gl_integration.h>
```

I'm asssssuuuuming that this is because libmesa-dev/libgl-dev etc - any chance the docker image can support that? Cheers

**Comment by anacierdem** [comment]
I build an opengl example without issues with the same includes. How do you think it relates to those? Also what do you mean choke 😊

**Comment by anacierdem** [comment]
Ok I had the chance to try this out, these are the steps you need to take to build it with the cli:

- Export `brewmodel.glb` from blender to `brew3d` folder as it is not part of the repository.
- Run `libdragon init` inside n64homebrew
- Run `git -C ./libdragon checkout opengl` to switch the branch as explained [here](https://github.com/anacierdem/libdragon-docker?tab=readme-ov-file#using-a-different-branch-of-libdragon) at the root
- Run `libdragon make` inside `brew3d`
