### ISSUE TITLE
Slim down image size

### ISSUE THREAD

**Issue by rasky** [anacierdem/libdragon-docker#8]
Currently, the image size is 1.33Gb. But it contains many things that can probably be pulled:

* `/usr/local/libexec/gcc/mips64-elf` is not stripped (574Mb -> 56Mb)
* `/usr/local/bin` is not stripped (110Mb -> 23Mb)
* `/usr/local/share/locale` is 13Mb, not so big but do we need translation messages for GCC?
* Running `apt-get remove gcc && apt autoremove` removes 200Mb of the native toolchain which is not needed.

**Comment by anacierdem** [comment]
We use the native GCC to build the tools etc. So it is not practical to remove it. I'm working on the others though. Also libdragon toolchain builds a new GCC to build the cross toolchain. We may remove that instead for some additional space gains.

**Comment by anacierdem** [comment]
Hmm or we should be able to use the new build for that, I think that was your suggestion. Let me see.

**Comment by anacierdem** [comment]
The dragon script removes the newly compiled native compiler, so I think we are good on that respect.
